name: Epitech Mirror

on:
  push:
    branches:
      - '**'

jobs:
  mirroring:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Push vers le dépôt Epitech
        env:
          TARGET_REPO: "github.com/EpitechPGE2-2025/G-YEP-400-STG-4-1-zappy-1.git"
          PAT: ${{ secrets.EPITECH_PAT }}
        run: |
          # Ajout du dépôt distant avec le token d'authentification intégré dans l'URL
          git remote add epitech "https://${PAT}@${TARGET_REPO}"
          
          # Push de toutes les branches et de tous les tags de manière forcée pour garantir le miroir exact
          git push epitech --all --force
          git push epitech --tags --force
